// Code generated for olezhek28 service
// © Olezhek28 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/arlengur/go-micros/grpc_with_layers_and_tests/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UFOService is an autogenerated mock type for the UFOService type
type UFOService struct {
	mock.Mock
}

type UFOService_Expecter struct {
	mock *mock.Mock
}

func (_m *UFOService) EXPECT() *UFOService_Expecter {
	return &UFOService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, info
func (_m *UFOService) Create(ctx context.Context, info model.SightingInfo) (string, error) {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SightingInfo) (string, error)); ok {
		return rf(ctx, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.SightingInfo) string); ok {
		r0 = rf(ctx, info)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.SightingInfo) error); ok {
		r1 = rf(ctx, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UFOService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UFOService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - info model.SightingInfo
func (_e *UFOService_Expecter) Create(ctx interface{}, info interface{}) *UFOService_Create_Call {
	return &UFOService_Create_Call{Call: _e.mock.On("Create", ctx, info)}
}

func (_c *UFOService_Create_Call) Run(run func(ctx context.Context, info model.SightingInfo)) *UFOService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SightingInfo))
	})
	return _c
}

func (_c *UFOService_Create_Call) Return(_a0 string, _a1 error) *UFOService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UFOService_Create_Call) RunAndReturn(run func(context.Context, model.SightingInfo) (string, error)) *UFOService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, uuid
func (_m *UFOService) Delete(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UFOService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UFOService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UFOService_Expecter) Delete(ctx interface{}, uuid interface{}) *UFOService_Delete_Call {
	return &UFOService_Delete_Call{Call: _e.mock.On("Delete", ctx, uuid)}
}

func (_c *UFOService_Delete_Call) Run(run func(ctx context.Context, uuid string)) *UFOService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UFOService_Delete_Call) Return(_a0 error) *UFOService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UFOService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *UFOService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *UFOService) Get(ctx context.Context, uuid string) (model.Sighting, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Sighting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Sighting, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Sighting); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Sighting)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UFOService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UFOService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UFOService_Expecter) Get(ctx interface{}, uuid interface{}) *UFOService_Get_Call {
	return &UFOService_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *UFOService_Get_Call) Run(run func(ctx context.Context, uuid string)) *UFOService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UFOService_Get_Call) Return(_a0 model.Sighting, _a1 error) *UFOService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UFOService_Get_Call) RunAndReturn(run func(context.Context, string) (model.Sighting, error)) *UFOService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, uuid, updateInfo
func (_m *UFOService) Update(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo) error {
	ret := _m.Called(ctx, uuid, updateInfo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.SightingUpdateInfo) error); ok {
		r0 = rf(ctx, uuid, updateInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UFOService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UFOService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - updateInfo model.SightingUpdateInfo
func (_e *UFOService_Expecter) Update(ctx interface{}, uuid interface{}, updateInfo interface{}) *UFOService_Update_Call {
	return &UFOService_Update_Call{Call: _e.mock.On("Update", ctx, uuid, updateInfo)}
}

func (_c *UFOService_Update_Call) Run(run func(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo)) *UFOService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.SightingUpdateInfo))
	})
	return _c
}

func (_c *UFOService_Update_Call) Return(_a0 error) *UFOService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UFOService_Update_Call) RunAndReturn(run func(context.Context, string, model.SightingUpdateInfo) error) *UFOService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUFOService creates a new instance of UFOService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUFOService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UFOService {
	mock := &UFOService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
